import 'package:floor/floor.dart';

/// Represents a reservation in the database.
///
/// The [Reservation] class is used to store information about a reservation,
/// including the IDs of the customer and flight associated with the reservation.
/// The [id] field is the primary key, which is auto-generated by the database.
@entity
class Reservation {
  /// Constructs a [Reservation] with the given customer and flight IDs.
  ///
  /// [customerId] is the ID of the customer making the reservation.
  /// [flightId] is the ID of the flight being reserved.
  /// [id] is the optional primary key for the reservation, which is auto-generated.
  Reservation(this.customerId, this.flightId, {this.id});

  /// Constructs a [Reservation] without the ID field.
  ///
  /// This constructor is used when creating a new reservation where the ID
  /// is not yet available. The [id] field is optional.
  Reservation.noid(this.customerId, this.flightId, {this.id});

  /// The primary key of the reservation. This field is auto-generated by the database.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  /// The ID of the customer who made the reservation.
  final int customerId;

  /// The ID of the flight being reserved.
  final int flightId;
}
